LogbookFilter: do not flush async response buffer if it had error
Do not flush buffer of the async response if it was known to have an
error previously. This should minimize stuff like "java.io.IOException:
Broken pipe" bubling up to onComplete() call which makes some servlet
containers complain about it quite loadly about it. E.g. on Tomcat:

WARN org.apache.catalina.core.AsyncContextImp: onComplete() call failed for listener of type [org.apache.catalina.core.AsyncListenerWrapper]
org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe
...
  at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:181)
  at org.zalando.logbook.servlet.LocalResponse.flushBuffer(LocalResponse.java:215)
  at org.zalando.logbook.servlet.LogbookFilter.write(LogbookFilter.java:86)
  at org.zalando.logbook.servlet.LogbookFilter.lambda$doFilter$0(LogbookFilter.java:71)
  at org.zalando.logbook.servlet.LogbookAsyncListener.onComplete(LogbookAsyncListener.java:17)
  at org.apache.catalina.core.AsyncListenerWrapper.fireOnComplete(AsyncListenerWrapper.java:39)
...